apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-api-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-api-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "get", "list", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-api-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: task-api-sa
  namespace: default
roleRef:
  kind: Role
  name: task-api-role
  apiGroup: rbac.authorization.k8s.io
