apiVersion: v1
kind: Service
metadata:
  name: task-api
  labels:
    app: task-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: task-api
